openapi: 3.0.3
info:
  title: Todo App API
  description: |-
    An API for managing todo tasks.
  version: 1.0-SNAPSHOT
servers:
  - url: https://todoapp.org/api/v1
tags:
  - name: tasks
    description: Operations related to tasks
paths:
  /tasks:
    get:
      tags:
        - tasks
      operationId: getTasks
      summary: Get a list of tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - tasks
      operationId: createTask
      summary: Create a new task
      requestBody:
        description: Task details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created task
        '400':
          description: Bad request


components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
